### ISSUE TITLE
Information Submission: Talmeez Fuaad

### ISSUE THREAD

**Issue by itstalmeez** [GDGCloudLahore/gdgcloudlahore#1]
### Personal Information

Please fill out the following details to help us know you better.

### Name
Talmeez Fuaad

### LinkedIn Profile Url[
[](https://www.linkedin.com/in/itstalmeez/)]

### Professional Information
As a data science enthusiast and an aspiring artificial intelligence professional, I am pursuing a bachelor's degree in AI at Arid Agriculture University, where I learn and apply the latest techniques and tools in the field. Python is my primary programming language, and I have developed multiple projects using machine learning, statistics, and data visualization libraries and frameworks.

I am also passionate about sharing my knowledge and skills with others, and I work as a data scientist at INTERNSAVY, an online platform that connects learners and mentors. Additionally, I have gained valuable industry experience as a data scientist at OneCrew Technologies, two leading technology companies that provide innovative solutions to various domains. I have contributed to several data-driven projects, such as building predictive models, analyzing customer behavior, and generating insights and recommendations.

### Cloud Level Expertise
Beginner

**Comment by adilshehzad786** [comment]
Hi Talmeez

We need your LinkedIn or Topmate URL to proceed. Thanks for the contribution.

**Comment by itstalmeez** [comment]
https://www.linkedin.com/in/itstalmeez/
https://topmate.io/itstalmeez
