### ISSUE TITLE
Information Submission: [Rao Shoaib Ur Rahman Khan]

### ISSUE THREAD

**Issue by raoshoaiburrahmankhan** [GDGCloudLahore/gdgcloudlahore#11]
### Personal Information

Please fill out the following details to help us know you better.

### LinkedIn Profile Url

https://www.linkedin.com/in/rao-shoaib-ur-rahman-khan-76b5a32a9?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app

### Professional Information

Computer Science Student 
### Cloud Level Expertise

Beginner 

### [Topmate.io](https://topmate.io/) Profile URL

https://topmate.io/rao_shoaib_ur_rahman_khan

**Comment by adilshehzad786** [comment]
Hi,

Thank you for your contribution. However, we are unable to proceed at this time as your profile does not meet the cloud mentorship requirements. I recommend connecting with an expert to learn from their experience. We wish you the best of luck. Thank you.
