### ISSUE TITLE
Muhammad Zunnurain Hussain

### ISSUE THREAD

**Issue by mzunnurainhussain** [GDGCloudLahore/gdgcloudlahore#4]
### Personal Information

Please fill out the following details to help us know you better.

### Name
Muhammad Zunnurain Hussain

### LinkedIn Profile Url
https://www.linkedin.com/in/muhammad-zunnurain-hussain-50641b61/

### Professional Information

Proven Network & Security specialist with comprehensive lifecycle advisory, client development, management, & technology consulting for fortune 100 clients. Strong client service with documented success cultivating relationships with senior clients across multiple advisory functions, resulting in the successful completion of projects, large-scale enterprise strategy implementation, & organization-wide transformations. Technical expertise presenting complex & technical terms to non-technical decision-makers and end-users. My passion lies in the design, implementation, & maintenance of Network & security systems. Keeping what's supposed to be private and proprietary safe.  In addition to having a number of certifications, I'm rather skilled at managing security policy practices, including both development & validation. I managed a remote (virtual) team.
From a business perspective, my risk-based analysis focus ensures that I'm thorough when doing Violation Tracking & Management, Patch Management, and Security Compliance Checking. I've led security implementation and management projects and their scoping including having tracked and managed projects to completion
### Cloud Level Expertise
 Advance

**Comment by adilshehzad786** [comment]
Your details have been added. Thank you for your contribution.
