### ISSUE TITLE
Information Submission: Usama Navid

### ISSUE THREAD

**Issue by concaption** [GDGCloudLahore/gdgcloudlahore#8]
### Personal Information

Please fill out the following details to help us know you better.

### Name
Usama Navid

### LinkedIn Profile Url
[https://www.linkedin.com/in/concaption](https://www.linkedin.com/in/concaption)

### Professional Information
My tech stack includes expertise in Pytorch, TensorFlow, Keras, and Sci-kit Learn, among others. I am currently focusing on MLOps and Data Engineering, and am always open to discussing emerging technologies and innovative engineering solutions.

### Cloud Level Expertise
Advance

### [Topmate.io](https://topmate.io/) Profile URL

[https://topmate.io/concaption](https://topmate.io/concaption)

**Comment by adilshehzad786** [comment]
Thanks Usama for the contributions. 🌟 You are now added to the mentorship page. Keep doing awesome work! 👍
